name: Build and Test Pyimgui

on:
  push:
    branches: [ "github-actions" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: python -m pip install --upgrade pip setuptools wheel
    - name: Install Build Requirements
      run: python -m pip install -r doc/requirements-dev.txt
    - name: Build
      run: make build
    - name: Install Test Requirements
      run: python -m pip install -r doc/requirements-test.txt
    - name: Run Tests
      run: py.test
